import type { Metadata } from "next";
import "./globals.css";
import ModalProvider from "@/providers/ModalProvider";
import SupabaseProvider from "@/providers/SupabaseProvider";
import ToasterProvider from "@/providers/ToasterProvider";

export const metadata: Metadata = {
  title: "Treinspotter App",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        <ToasterProvider />
        <SupabaseProvider>
          <ModalProvider />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
