-- Enable extensions
create extension if not exists "uuid-ossp";
create extension if not exists postgis;

-- User profiles (linked to auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- Train stations with geolocation
create table if not exists public.train_stations (
  id bigint generated by default as identity primary key,
  name text not null,
  country_code char(2),
  station_code text,
  longitude numeric(9, 6),
  latitude numeric(9, 6),
  location geography(point, 4326),
  created_at timestamptz not null default now()
);

-- Train types
create table if not exists public.train_types (
  id bigint generated by default as identity primary key,
  name text not null,
  class_name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

-- Train operators
create table if not exists public.train_operators (
  id bigint generated by default as identity primary key,
  name text not null unique,
  country_code char(2),
  slug text not null unique,
  created_at timestamptz not null default now()
);

-- Individual trains
create table if not exists public.trains (
  id bigint generated by default as identity primary key,
  train_number text not null unique,
  alt_number text,
  train_type_id bigint references public.train_types(id) on delete set null,
  operator_id bigint references public.train_operators(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists trains_train_type_id_idx on public.trains(train_type_id);
create index if not exists trains_operator_id_idx on public.trains(operator_id);

-- Trainspotter image location
create table if not exists public.train_image_locations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  station_id bigint references public.train_stations(id) on delete set null,
  location_type text not null check (location_type in ('station', 'route')),
  station_id_end bigint references public.train_stations(id) on delete set null,
  constraint location_station_check check (
    (location_type = 'station' and station_id is not null and station_id_end is null) or
    (location_type = 'route' and station_id is not null and station_id_end is not null)
  ),
  created_at timestamptz not null default now()
);

create index if not exists train_image_locations_user_id_idx on public.train_image_locations(user_id);
create index if not exists train_image_locations_station_id_idx on public.train_image_locations(station_id);
create index if not exists train_image_locations_station_id_end_idx on public.train_image_locations(station_id_end);

-- Trainspotter images and metadata
create table if not exists public.train_images (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  location_id bigint references public.train_image_locations(id) on delete set null,
  train_type_id bigint references public.train_types(id) on delete set null,
  train_id bigint references public.trains(id) on delete set null,
  title text,
  description text,
  taken_at timestamptz,
  is_private boolean not null default false,
  image_path text not null,
  mime_type text,
  file_size_bytes bigint,
  width_px integer,
  height_px integer,
  original_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists train_images_user_id_idx on public.train_images(user_id);
create index if not exists train_images_location_id_idx on public.train_images(location_id);
create index if not exists train_images_train_type_id_idx on public.train_images(train_type_id);
create index if not exists train_images_train_id_idx on public.train_images(train_id);

-- Storage bucket
insert into storage.buckets (id, name, public)
values ('train-images', 'train-images', true)
on conflict (id) do nothing;

-- RLS on tables
alter table public.profiles enable row level security;
alter table public.train_stations enable row level security;
alter table public.train_types enable row level security;
alter table public.train_operators enable row level security;
alter table public.trains enable row level security;
alter table public.train_images enable row level security;
-- alter table public.train_image_locations enable row level security;

-- Profiles policies
create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = id);

create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = id);

create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id);

-- Stations policies (readable by everyone, managed by admins)
create policy "stations_select_all" on public.train_stations
for select using (true);

create policy "stations_insert_auth" on public.train_stations
for insert with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "stations_update_auth" on public.train_stations
for update using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "stations_delete_auth" on public.train_stations
for delete using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

-- Train types policies (readable by everyone, managed by admins)
create policy "train_types_select_all" on public.train_types
for select using (true);

create policy "train_types_insert_auth" on public.train_types
for insert with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "train_types_update_auth" on public.train_types
for update using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "train_types_delete_auth" on public.train_types
for delete using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

-- Train operators policies (readable by everyone, managed by admins)
create policy "train_operators_select_all" on public.train_operators
for select using (true);

create policy "train_operators_insert_auth" on public.train_operators
for insert with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "train_operators_update_auth" on public.train_operators
for update using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "train_operators_delete_auth" on public.train_operators
for delete using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

-- Trains policies (readable by everyone, managed by admins)
create policy "trains_select_all" on public.trains
for select using (true);

create policy "trains_insert_auth" on public.trains
for insert with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "trains_update_auth" on public.trains
for update using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

create policy "trains_delete_auth" on public.trains
for delete using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid() and is_admin = true
  )
);

-- Images policies
create policy "train_images_select_public_or_own" on public.train_images
for select using (is_private = false or auth.uid() = user_id);

create policy "train_images_insert_own" on public.train_images
for insert with check (auth.uid() = user_id);

create policy "train_images_update_own" on public.train_images
for update using (auth.uid() = user_id);

create policy "train_images_delete_own" on public.train_images
for delete using (auth.uid() = user_id);

-- -- Loations policies
-- create policy "train_image_locations_select_public_or_own" on public.train_image_locations
-- for select using (
--   exists (
--     select 1
--     from public.train_images
--     where public.train_images.location_id = public.train_image_locations.id
--       and (public.train_images.is_private = false or public.train_images.user_id = auth.uid())
--   )
-- );
-- create policy "train_image_locations_insert_own" on public.train_image_locations
-- for insert with check (auth.uid() = user_id);

-- create policy "train_image_locations_update_own" on public.train_image_locations
-- for update using (auth.uid() = user_id);

-- create policy "train_image_locations_delete_own" on public.train_image_locations
-- for delete using (auth.uid() = user_id);

-- Storage policies (public reads, owner writes)
create policy "storage_read_train_images" on storage.objects
for select using (bucket_id = 'train-images');

create policy "storage_write_own_train_images" on storage.objects
for insert with check (bucket_id = 'train-images' and auth.uid() = owner);

create policy "storage_delete_own_train_images" on storage.objects
for delete using (bucket_id = 'train-images' and auth.uid() = owner);